version: "3.9"

services:
  postgres-services:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-services
    environment:
      DEBUG: 1
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres-services
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data:
