version: "3.9"

services:
  postgres-service:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  django-service:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-service
      - redis
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres-service
      POSTGRES_PORT: 5432

  # worker:
  #   build: .
  #   command: celery -A app worker --loglevel=INFO
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - postgres-service
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_HOST: postgres-service
  #     POSTGRES_PORT: 5432

  # beat:
  #   build: .
  #   command: celery -A app beat --loglevel=INFO
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - postgres-service
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_HOST: postgres-service
  #     POSTGRES_PORT: 5432

  worker:
    build: .
    command: python app/manage.py rqworker default
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
